default_platform(:android)

platform :android do
  desc "Compila de forma local el APK firmado (Release Build) usando Gradle"
  lane :build_release do
    # Ejecuta el task assembleRelease de Gradle
    gradle(
      task: "assemble",
      build_type: "Release"
    )
    
    UI.success("¡Éxito! Tu APK firmado se ha generado correctamente en:")
    UI.message("👉 app/build/outputs/apk/release/app-release.apk")
  end
end
